# Generated by Django 4.0.5 on 2022-07-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboard',
            old_name='buildname',
            new_name='name',
        ),
    ]
